id: D4AFB72FE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:47:31+00:00'
last_modified: '2022-05-27T15:01:06.037166+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    4a54:
      image_group_id: I1PD95908
      title: བདེན་པ་གཉིས་ལ་འཇུག་པ།
      total_pages: 1926
      order: 63
      base_file: 4a54.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
