id: PBD077E47
initial_creation_type: ocr
source_metadata:
  volumes:
    d886026e18b142a3aa963a99f1274ca4:
      base_file: v063.txt
      image_group_id: I1PD95908
      title: བདེན་པ་གཉིས་ལ་འཇུག་པ།
      total_pages: 1926
      volume_number: 63
